name: Black Bear Cinematography
favicon: null
layout_spectrum: 0.2964274992700666
typography_spectrum: 0.6368021292146295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23848835192620754
  lightness: 0.9155561565421522
  saturation: 0.7764734940137714
  rhythmicContrast: 0.48583928612060845
purpose: []
